# Generated by Django 4.2.2 on 2023-06-27 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('Login', models.TextField(max_length=255)),
                ('Senha', models.TextField(max_length=10)),
            ],
        ),
    ]
