# Generated by Django 4.2.2 on 2023-06-27 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='Login',
            new_name='login',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Senha',
            new_name='senha',
        ),
    ]
